sudo: false
language: android
jdk:
  - oraclejdk8

android:
    components:
#      - build-tools-24.0.0 rc1
#      - build-tools-23.0.1
#      - build-tools-23.0.2
#      - build-tools-25.0.0
      - android-23
      - extra

before_script:
  - chmod +x gradlew

script:
    - ./gradlew check --info

